### ISSUE TITLE
I can't change conpot template

### ISSUE THREAD

**Issue by sfigue** [dtag-dev-sec/tpotce#162]
Hi,

I tried to use conpot, since tpot 17.10. When i ran the default template with (conpot -t default) sended me:

...
2017-12-19 06:51:05,543 Found and enabled ('snmp', <class 'conpot.protocols.snmp.snmp_server.SNMPServer'>) protocol.
2017-12-19 06:51:05,544 Conpot Bacnet initialized using the /usr/local/lib/python2.7/dist-packages/Conpot-0.5.1-py2.7.egg/conpot/templates/default/bacnet/bacnet.xml template.
2017-12-19 06:51:05,544 Found and enabled ('bacnet', <class 'conpot.protocols.bacnet.bacnet_server.BacnetServer'>) protocol.
2017-12-19 06:51:05,545 IPMI BMC initialized.
2017-12-19 06:51:05,545 Conpot IPMI initialized using /usr/local/lib/python2.7/dist-packages/Conpot-0.5.1-py2.7.egg/conpot/templates/default/ipmi/ipmi.xml template
2017-12-19 06:51:05,546 Found and enabled ('ipmi', <class 'conpot.protocols.ipmi.ipmi_server.IpmiServer'>) protocol.
2017-12-19 06:51:05,547 Class 22/0x0016, Instance 1, Attribute 1 <== [{'class': 22}, {'instance': 1}, {'attribute': 1}]
2017-12-19 06:51:05,547 Class 22/0x0016, Instance 1, Attribute 2 <== [{'class': 22}, {'instance': 1}, {'attribute': 2}]
2017-12-19 06:51:05,547 Class 22/0x0016, Instance 1, Attribute 1 <== [{'class': 22}, {'instance': 1}, {'attribute': 1}]
2017-12-19 06:51:05,548 Class 22/0x0016, Instance 1, Attribute 3 <== [{'class': 22}, {'instance': 1}, {'attribute': 3}]
2017-12-19 06:51:05,548 Class 22/0x0016, Instance 1, Attribute 2 <== [{'class': 22}, {'instance': 1}, {'attribute': 2}]
2017-12-19 06:51:05,548 Class 22/0x0016, Instance 1, Attribute 1 <== [{'class': 22}, {'instance': 1}, {'attribute': 1}]
2017-12-19 06:51:05,548 Found and enabled ('enip', <class 'conpot.protocols.enip.enip_server.EnipServer'>) protocol.
2017-12-19 06:51:05,548 No proxy template found. Service will remain unconfigured/stopped.
2017-12-19 06:51:05,548 Modbus server started on: ('0.0.0.0', 502)
2017-12-19 06:51:05,549 S7Comm server started on: ('0.0.0.0', 102)
2017-12-19 06:51:05,554 HTTP server started on: ('0.0.0.0', 80)
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
result = self._run(*self.args, **self.kwargs)
File "/usr/local/lib/python2.7/dist-packages/Conpot-0.5.1-py2.7.egg/conpot/protocols/snmp/snmp_server.py", line 180, in start
self.cmd_responder = CommandResponder(host, port, self.compiled_mibs)
File "/usr/local/lib/python2.7/dist-packages/Conpot-0.5.1-py2.7.egg/conpot/protocols/snmp/command_responder.py", line 78, in init
config.addV1System(self.snmpEngine, 'public-read', 'public')
File "/usr/local/lib/python2.7/dist-packages/pysnmp-4.3.9-py2.7.egg/pysnmp/entity/config.py", line 78, in addV1System
((snmpCommunityEntry.name + (8,) + tblIdx, 'destroy'),)
File "/usr/local/lib/python2.7/dist-packages/pysnmp-4.3.9-py2.7.egg/pysnmp/smi/instrum.py", line 256, in writeVars
return self.flipFlopFsm(self.fsmWriteVar, varBinds, acInfo)
File "/usr/local/lib/python2.7/dist-packages/pysnmp-4.3.9-py2.7.egg/pysnmp/smi/instrum.py", line 239, in flipFlopFsm
raise origExc
WrongValueError: WrongValueError({'msg': WrongValueError(), 'name': (1, 3, 6, 1, 6, 3, 18, 1, 1, 1, 4, 112, 117, 98, 108, 105, 99, 45, 114, 101, 97, 100), 'idx': 0})
Tue Dec 19 06:51:05 2017 <Greenlet at 0x7f03ad2714b0: <bound method SNMPServer.start of <conpot.protocols.snmp.snmp_server.SNMPServer object at 0x7f03ad2c45d0>>('0.0.0.0', 161)> failed with WrongValueError

2017-12-19 06:51:05,896 Bacnet server started on: ('0.0.0.0', 47808)
2017-12-19 06:51:05,896 IPMI server started on: ('0.0.0.0', 623)
2017-12-19 06:51:05,897 handle server PID [ 3188] running on ('0.0.0.0', 44818)
2017-12-19 06:51:05,897 handle server PID [ 3188] responding to external done/disable signal in object 139653767458448
ERROR:root:Stopping because <Greenlet at 0x7f03ad2714b0: <bound method SNMPServer.start of <conpot.protocols.snmp.snmp_server.SNMPServer object at 0x7f03ad2c45d0>>('0.0.0.0', 161)> died: WrongValueError({'msg': WrongValueError(), 'name': (1, 3, 6, 1, 6, 3, 18, 1, 1, 1, 4, 112, 117, 98, 108, 105, 99, 45, 114, 101, 97, 100), 'idx': 0})
2017-12-19 06:51:05,897 Stopping because <Greenlet at 0x7f03ad2714b0: <bound method SNMPServer.start of <conpot.protocols.snmp.snmp_server.SNMPServer object at 0x7f03ad2c45d0>>('0.0.0.0', 161)> died: WrongValueError({'msg': WrongValueError(), 'name': (1, 3, 6, 1, 6, 3, 18, 1, 1, 1, 4, 112, 117, 98, 108, 105, 99, 45, 114, 101, 97, 100), 'idx': 0})

Then, i tried to upgrade pysnmp with (easy_install --upgrade pysnmp) and had a new issue (Unable to execute 'gcc': No such file or directory).
Then i applied (apk add --no-cache gcc) and i had a new issue (gcc:stdio.h: No such file or directory).

Any solution?

Thanks.

**Comment by t3chn0m4g3** [comment]
Conpot is designed to run a certain [configuration set](https://github.com/dtag-dev-sec/tpotce/tree/master/docker/conpot/dist) within T-Pot.

Changes to that config will involve changes to:
1. `/opt/tpot/tpot.yml` (since different ports will be used for container start & adding a volume for the container config where to load your config from)
2. `/etc/systemd/system/tpot.service` (since iptables exclusions need to be modified according to the ports of the Conpot config changes)

Best starting point will be [Conpot's Dockerfile](https://github.com/dtag-dev-sec/tpotce/tree/master/docker/conpot). Please be reminded that most of the docker images run Alpine Linux which has different dependencies than Ubuntu based distros.

Please understand that we cannot post a full tutorial on Docker / Conpot and configuration sets.

Thank you :bowtie:

**Comment by t3chn0m4g3** [comment]
Assuming this is solved.
