### ISSUE TITLE
Cowrie docker in tpot does not build

### ISSUE THREAD

**Issue by cryptax** [dtag-dev-sec/tpotce#290]
I wanted to tweak Cowrie used in T-Pot, but actually, it does not build as such currently. See steps to reproduce below:

**Reproduce**:
- Clone the latest sources: `git clone https://github.com/dtag-dev-sec/tpotce`
- In tpotce, go to `./docker/cowrie` and run `docker-compose up --build`

You get this error:

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 346, in run
    session=session, autobuilding=True
  File "/usr/lib/python2.7/site-packages/pip/_internal/wheel.py", line 886, in build
    assert have_directory_for_build
AssertionError
ERROR: Service 'cowrie' failed to build: The command '/bin/sh -c apk -U --no-cache add                        build-base                        git                        gmp-dev                        libcap                        libffi-dev                        mpc1-dev                        mpfr-dev                        openssl-dev                        python                        python-dev                        py-mysqldb                        py-pip                        py-requests                        py-setuptools &&     addgroup -g 2000 cowrie &&     adduser -S -s /bin/ash -u 2000 -D -g 2000 cowrie &&     git clone --depth=1 https://github.com/micheloosterhof/cowrie /home/cowrie/cowrie/ -b v1.3.0 &&     cd /home/cowrie/cowrie &&     pip install --no-cache-dir --upgrade cffi pip &&     pip install --no-cache-dir --upgrade -r requirements.txt &&     setcap cap_net_bind_service=+ep /usr/bin/python2.7 &&     cp /root/dist/cowrie.cfg /home/cowrie/cowrie/cowrie.cfg &&     chown cowrie:cowrie -R /home/cowrie/* /usr/lib/python2.7/site-packages/twisted/plugins &&     su - cowrie -c "export PYTHONPATH=/home/cowrie/cowrie &&                    cd /home/cowrie/cowrie &&                    /usr/bin/twistd --uid=2000 --gid=2000 -y cowrie.tac --pidfile cowrie.pid cowrie &" &&     sleep 10 &&     apk del --purge build-base                     git                     gmp-dev                     libcap                     libffi-dev                     mpc1-dev                     mpfr-dev                     python-dev                     py-mysqldb                     py-pip &&     rm -rf /root/* &&     rm -rf /var/cache/apk/* &&     rm -rf /home/cowrie/cowrie/cowrie.pid' returned a non-zero code: 2
```

**Comment by t3chn0m4g3** [comment]
This is related to pip, a fix will be available in a couple of days (according to the issue).
https://github.com/pypa/pip/issues/6197

Closing this, because it is an upstream bug.

**Comment by cryptax** [comment]
Indeed, and as referenced in that issue, a **workaround** is to use pip 18.1. So, for the Dockerfile, if you simply do not upgrade pip, the image builds:

Replace
   `pip install --no-cache-dir --upgrade cffi pip && \`

with: 
   `pip install --no-cache-dir --upgrade cffi && \`

Thanks.

**Comment by t3chn0m4g3** [comment]
@cryptax thank you.
