### ISSUE TITLE
Unhandled exception (KeyError)

### ISSUE THREAD

**Issue by workandresearchgithub** [dtag-dev-sec/tpotce#313]
### Basic support information

- What T-Pot version are you currently using?
- Are you running on a Intel NUC or a VM?
- direct hardware install to an I5 w/8 gig of RAM
- How long has your installation been running?
1 day
- Did you install any upgrades or packages?
No.  I ran update.sh -y though.
- Did you modify any scripts?
No
- Have you turned persistence on/off?
not intentionally
- How much RAM is available (login via ssh and run `htop`)?
4.38G/7.52G
- How much stress are the CPUs under (login via ssh and run `htop`)?
5%
- How much swap space is being used (login via ssh and run `htop`)?
780k/7.63G
- How much free disk space is available (login via ssh and run `sudo df -h`)?
96% free
- What is the current container status (login via ssh and run `sudo dps.sh`)?
```
========| System |========
    Date:  Sat Mar  9 14:28:29 CST 2019
  Uptime:  14:28:29 up 11:00,  1 user,  load average: 0.16, 0.35, 0.44
CPU temp:

NAME                  STATUS                       PORTS
adbhoney              Up 3 hours             0.0.0.0:5555->5555/tcp
ciscoasa              Up 3 hours
conpot_guardian_ast   Up 3 hours             0.0.0.0:10001->10001/tcp
conpot_iec104         Up 3 hours             0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 3 hours             0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 3 hours             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 3 hours             0.0.0.0:22-23->22-23/tcp
cyberchef             Up 3 hours (healthy)   127.0.0.1:64299->8000/tcp
dionaea               Up 3 hours
elasticpot            Up 3 hours             0.0.0.0:9200->9200/tcp
elasticsearch         Up 3 hours (healthy)   127.0.0.1:64298->9200/tcp
head                  Up 3 hours (healthy)   127.0.0.1:64302->9100/tcp
heralding             Up 3 hours             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeytrap             Up 3 hours
kibana                Up 3 hours (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up 3 hours (healthy)
mailoney              Up 3 hours             0.0.0.0:25->25/tcp
medpot                Up 3 hours             0.0.0.0:2575->2575/tcp
nginx                 Up 3 hours
p0f                   Up 3 hours
rdpy                  Up 3 hours             0.0.0.0:3389->3389/tcp
snare                 Up 3 hours             0.0.0.0:80->80/tcp
spiderfoot            Up 3 hours (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 3 hours
tanner                Up 3 hours
tanner_api            Up 3 hours
tanner_phpox          Up 3 hours
tanner_redis          Up 3 hours             6379/tcp
tanner_web            Up 3 hours
--
```

Here is the error message from spiderfoot:
```
--
Unhandled exception (KeyError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 338, in processHost\n    self.processDomain(dom, evt)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 357, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsbrute.py", line 131, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 222, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_bingsharedip.py", line 133, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 262, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 286, in spiderFrom\n    links = self.processUrl(startingPoint)  # fetch first page\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 107, in processUrl\n    self.contentNotify(url, fetched, self.urlEvents[url])\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 199, in contentNotify\n    self.notifyListeners(event)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_email.py", line 98, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_fullcontact.py", line 151, in handleEvent\n    e = SpiderFootEvent("HUMAN_NAME", data[\'fullName\'], self.__name__, event)\n', "KeyError: 'fullName'\n"]
--
```

spiderfoot is aware of the issue, and believes they have resolved it (https://github.com/smicallef/spiderfoot/issues/242).  The solution they recommended is to obtain the latest version.

**Comment by t3chn0m4g3** [comment]
@workandresearchgithub Thanks for bringing this to my attention. Will fix it for the next release 19.03.

**Comment by t3chn0m4g3** [comment]
@workandresearchgithub Right now the new Docker image is building on DockerHub (give it 30 minutes or so). Please install the [19.03 beta](https://github.com/dtag-dev-sec/tpotce/releases/tag/19.03.beta) and let me know if the fix works for you, too.

**Comment by workandresearchgithub** [comment]
will do.  Is that as simple as "./update.sh -y"   ?

**Comment by t3chn0m4g3** [comment]
You will have to install the new ISO. If you wait long enough the new docker image will be pulled automagically.

**Comment by t3chn0m4g3** [comment]
Image finished building. You can install the beta now. Please be reminded this is just for testing purposes, the final release needs a fresh install.

**Comment by workandresearchgithub** [comment]
in the midst of installing.  might take me awhile as the system is an old toshiba laptop with a 5400rpm drive......

btw, when do you anticipate making this release the stable version?

**Comment by t3chn0m4g3** [comment]
Release by the end of this month.

**Comment by t3chn0m4g3** [comment]
Closing this as resolved.
