### ISSUE TITLE
/var/log filling up : due to ewsposter?

### ISSUE THREAD

**Issue by atbohmer** [dtag-dev-sec/tpotce#348]
Hello,

Since a few days the whole system locks up due to /var/log filling up (used a simple partition scheme, just /). Both daemon.log and syslog are growing rapid in size up to a total of 50GB on a daily basis.

An entry which is inserted quite regulary is this one:
```
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              | EWS Poster v1.9.6 (c) by Markus Schroer <markus.schroer@telekom.de>
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |  => Using external IP address x.x.x.x
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              | Traceback (most recent call last):
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |   File "/opt/ewsposter/ews.py", line 2595, in <module>
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |     ECFG = ecfg(name,version)
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |   File "/opt/ewsposter/moduls/einit.py", line 233, in ecfg
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |     HCFG = readcfg("HPFEED",ITEMS, ECFG["cfgfile"])
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |   File "/opt/ewsposter/moduls/etoolbox.py", line 73, in readcfg
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |     if config.has_option(MODULE,items) is True and len(config.get(MODULE,items)) > 0:
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |   File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |     return self._interpolate(section, option, value, d)
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |   File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |     self._interpolate_some(option, L, rawval, section, vars, 1)
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |   File "/usr/lib/python2.7/ConfigParser.py", line 723, in _interpolate_some
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              |     option, section, rest, var)
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              | ConfigParser.InterpolationMissingOptionError: Bad value substitution:
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              | #011section: [HPFEED]
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              | #011option : hpfeed
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              | #011key    : ews_hpfeeds_enable
Apr 12 07:29:21 liabledictionary docker-compose[20520]: ewsposter              | #011rawval :
```

Any idea how to stop this sudden increase of both files? Any other info needed?

Running T-Pot 19.03.0 on an ESX VM 4 cores, 8GB memory and 60GB disk (8GB swap).

Best regards,
Andre

**Comment by t3chn0m4g3** [comment]
From the looks of it the `tpot.yml` was modified, please post `/opt/tpot/etc/tpot.yml`.

**Comment by atbohmer** [comment]
Please find attached zipped file
[tpot.yml.gz](https://github.com/dtag-dev-sec/tpotce/files/3072559/tpot.yml.gz)

**Comment by t3chn0m4g3** [comment]
Thanks. I pulled the `18.11` ewsposter image and ran it without problems:
```
ewsposter    | EWS Poster v1.9.6 (c) by Markus Schroer <markus.schroer@telekom.de>
ewsposter    | 
ewsposter    |  => Create ews.idx counterfile
ewsposter    |  => Using external IP address 87.150.227.53
ewsposter    |  => Create lock socket successfull.
ewsposter    |  => Sender : No Jobs to send in /opt/ewsposter/spool/
ewsposter    |  => Starting Glastopf V3.x Modul.
ewsposter    |     => [GLASTOPFV3] [INFO] Sqlitedb /data/glastopf/db/glastopf.db is corrupt or does not contain events. Skipping ! 
ewsposter    |  => Starting Dionaea Modul.
ewsposter    |     -> 22 EWS alert records send ...
ewsposter    |  => Starting Honeytrap Modul.
ewsposter    |     -> Calculate MD5sum for Payload Files
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting Conpot Modul.
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting Cowrie Modul.
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 100 log entries processed ...
ewsposter    |     -> 200 log entries processed ...
ewsposter    |     -> 300 log entries processed ...
ewsposter    |     -> 400 log entries processed ...
ewsposter    |     -> 500 log entries processed ...
ewsposter    |  => Starting Elasticpot Modul.
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting Suricata Modul.
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 100 log entries processed ...
ewsposter    |     -> 200 log entries processed ...
ewsposter    |     -> 300 log entries processed ...
ewsposter    |     -> 400 log entries processed ...
ewsposter    |     -> 500 log entries processed ...
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting RDPY Modul.
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 100 log entries processed ...
ewsposter    |     -> 200 log entries processed ...
ewsposter    |     -> 300 log entries processed ...
ewsposter    |     -> 400 log entries processed ...
ewsposter    |     -> 500 log entries processed ...
ewsposter    |     -> 249 EWS alert records send ...
ewsposter    |  => Starting MAILONEY Modul.
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 1 EWS alert records send ...
ewsposter    |  => Starting VNCLOWPOT Modul.
ewsposter    |     => [VNCLOWPOT] [ERROR] Missing LogFile /data/vnclowpot/log/vnclowpot.log. Skip !
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting HERALDING Modul.
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 100 log entries processed ...
ewsposter    |     -> 107 EWS alert records send ...
ewsposter    |  => Starting CISCO-ASA Modul.
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 0 EWS alert records send ...
ewsposter    |  => Starting Tanner Modul.
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 100 log entries processed ...
ewsposter    |     -> 200 log entries processed ...
ewsposter    |     -> 300 log entries processed ...
ewsposter    |     -> 400 log entries processed ...
ewsposter    |     -> 412 EWS alert records send ...
ewsposter    |  => Starting Glutton Modul.
ewsposter    |  => Send Limit is set to : 500. Adapting to limit!
ewsposter    |     -> 100 log entries processed ...
ewsposter    |     -> 200 log entries processed ...
ewsposter    |     -> 300 log entries processed ...
ewsposter    |     -> 400 log entries processed ...
ewsposter    |     -> 500 log entries processed ...
ewsposter    |     -> 304 EWS alert records send ...
ewsposter    |  => Sleeping for 60 seconds ....
```

Can you verify, if the following files exist (`ls -al`)?
```
/opt/tpot/etc/compose/elk_environment
/data/ews/conf/ews.ip:/opt/ewsposter/ews.ip
```

Installing 19.03 from scratch might resolve things faster.

**Comment by t3chn0m4g3** [comment]
On a second look. The `tpot.yml` you posted does not match your T-Pot 19.03 installation.

**Comment by atbohmer** [comment]
Is was a fresh T-Pot install, including a format of the drive.

**Comment by t3chn0m4g3** [comment]
The `tpot.yml` is a link to one of the edition configs and it is bound to 1903 for ewsposter with regard to `standard.yml`:
https://github.com/dtag-dev-sec/tpotce/blob/master/etc/compose/standard.yml#L504-L524

**Comment by atbohmer** [comment]
Thanks, I'll use this one and if the problem persist perform a new fresh install.

**Comment by t3chn0m4g3** [comment]
Thanks for the update. Assuming this is resolved.
