### ISSUE TITLE
cowrie does not listen 22 and 23 ports

### ISSUE THREAD

**Issue by tyghr** [dtag-dev-sec/tpotce#378]
```
Debian GNU/Linux 8.11 (jessie)
```

Using single docker image dtagdevsec/cowrie:1903
I just start it with sample docker-compose file

```
version: '2.3'

networks:
  cowrie_local:

services:

  cowrie:
    container_name: cowrie
    restart: always
    tmpfs:
     - /tmp/cowrie:uid=2000,gid=2000
     - /tmp/cowrie/data:uid=2000,gid=2000
    networks:
     - cowrie_local
    ports:
     - "2222:22"
     - "2223:23"
    image: "dtagdevsec/cowrie:1903"
    #read_only: true
```

docker-compose -f tpot.yml up

and it saying that it cannot start listen on ports 22 and 23
```
Recreating cowrie ... done
Attaching to cowrie
cowrie    | 2019-05-24T17:44:11+0000 [-] Python Version 2.7.15 (default, Jan 24 2019, 16:32:39) [GCC 8.2.0]
cowrie    | 2019-05-24T17:44:11+0000 [-] Twisted Version 18.9.0
cowrie    | 2019-05-24T17:44:11+0000 [-] Loaded output engine: jsonlog
cowrie    | 2019-05-24T17:44:11+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.9.0 (/usr/bin/python2 2.7.15) starting up.
cowrie    | 2019-05-24T17:44:11+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
cowrie    | 2019-05-24T17:44:11+0000 [-] Unhandled Error
cowrie    |     Traceback (most recent call last):
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/application/service.py", line 283, in privilegedStartService
cowrie    |         service.privilegedStartService()
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/application/service.py", line 283, in privilegedStartService
cowrie    |         service.privilegedStartService()
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/application/internet.py", line 360, in privilegedStartService
cowrie    |         self._waitingForPort = self.endpoint.listen(self.factory)
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 488, in listen
cowrie    |         interface=self._interface)
cowrie    |     --- <exception caught here> ---
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 122, in execute
cowrie    |         result = callable(*args, **kw)
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
cowrie    |         p.startListening()
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1363, in startListening
cowrie    |         raise CannotListenError(self.interface, self.port, le)
cowrie    |     twisted.internet.error.CannotListenError: Couldn't listen on 0.0.0.0:22: [Errno 13] Permission denied.
cowrie    |
cowrie    | 2019-05-24T17:44:11+0000 [-] Unhandled Error
cowrie    |     Traceback (most recent call last):
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/application/service.py", line 283, in privilegedStartService
cowrie    |         service.privilegedStartService()
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/application/service.py", line 283, in privilegedStartService
cowrie    |         service.privilegedStartService()
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/application/internet.py", line 360, in privilegedStartService
cowrie    |         self._waitingForPort = self.endpoint.listen(self.factory)
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 488, in listen
cowrie    |         interface=self._interface)
cowrie    |     --- <exception caught here> ---
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 122, in execute
cowrie    |         result = callable(*args, **kw)
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
cowrie    |         p.startListening()
cowrie    |       File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1363, in startListening
cowrie    |         raise CannotListenError(self.interface, self.port, le)
cowrie    |     twisted.internet.error.CannotListenError: Couldn't listen on 0.0.0.0:23: [Errno 13] Permission denied.
cowrie    |
q^CGracefully stopping... (press Ctrl+C again to force)
Stopping cowrie   ... done
```

**Comment by t3chn0m4g3** [comment]
Not supported.

**Comment by tyghr** [comment]
i'm sorry, which thing is not supported?
docker image dtagdevsec/cowrie ?

**Comment by t3chn0m4g3** [comment]
The images are only supported within an install of T-Pot which has to run on Debian Sid / 10 / Buster.

**Comment by tyghr** [comment]
ok, thank you for the answer.
