### ISSUE TITLE
issue Twisted Not an issue TPOT issue

### ISSUE THREAD

**Issue by iukea1** [dtag-dev-sec/tpotce#381]
This is not a TPOT issue just a issue I am having with one of the docker containers being cowire and RDPY (saw that you updated RDPYs docker code and that worked) 

Also linked this issue over on Cowire page 
[](https://github.com/cowrie/cowrie/issues/1137)

Getting the same issue about Twisted now with Cowire

did

`docker logs -f cowrie`

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/python/usage.py", line 447, in __str__
    return self.getSynopsis() + '\n' + self.getUsage(width=None)
  File "/usr/lib/python2.7/site-packages/twisted/python/usage.py", line 484, in getUsage
    for (cmd, short, parser, desc) in self.subCommands:
  File "/usr/lib/python2.7/site-packages/twisted/application/app.py", line 653, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
  File "/usr/lib/python2.7/site-packages/twisted/plugin.py", line 213, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/plugin.py", line 171, in getCache
    provider = pluginModule.load()
  File "/usr/lib/python2.7/site-packages/twisted/python/modules.py", line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python2.7/site-packages/twisted/python/reflect.py", line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python2.7/site-packages/twisted/python/reflect.py", line 255, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/home/cowrie/cowrie/src/twisted/plugins/cowrie_plugin.py", line 45, in <module>
    import cowrie.core.checkers
  File "/home/cowrie/cowrie/src/cowrie/core/checkers.py", line 13, in <module>
    from twisted.conch.ssh import keys
  File "/usr/lib/python2.7/site-packages/twisted/conch/ssh/keys.py", line 18, in <module>
    import bcrypt
exceptions.ImportError: No module named bcrypt

Usage: twistd [options]
Options:
  -b, --debug          Run the application in the Python Debugger (implies
                       nodaemon),         sending SIGUSR2 will drop into
                       debugger
      --chroot=        Chroot to a supplied directory before running
  -d, --rundir=        Change to a supplied directory before running [default:
                       .]
  -e, --encrypted      The specified tap/aos file is encrypted.
      --euid           Set only effective user-id rather than real user-id.
                       (This option has no effect unless the server is running
                       as root, in which case it means not to shed all
                       privileges after binding ports, retaining the option to
                       regain privileges in cases such as spawning processes.
                       Use with caution.)
  -f, --file=          read the given .tap file [default: twistd.tap]
  -g, --gid=           The gid to run as.  If not specified, the default gid
                       associated with the specified --uid is used.
      --help           Display this help and exit.
      --help-reactors  Display a list of possibly available reactor names.
  -l, --logfile=       log to a specified file, - for stdout
      --logger=        A fully-qualified name to a log observer factory to use
                       for the initial log observer.  Takes precedence over
                       --logfile and --syslog (when available).
  -n, --nodaemon       don't daemonize, don't use default umask of 0077
  -o, --no_save        do not save state on shutdown
      --originalname   Don't try to change the process name
  -p, --profile=       Run in profile mode, dumping results to specified file.
      --pidfile=       Name of the pidfile [default: twistd.pid]
      --prefix=        use the given prefix when syslogging [default: twisted]
      --profiler=      Name of the profiler to use (profile, cprofile).
                       [default: cprofile]
  -r, --reactor=       Which reactor to use (see --help-reactors for a list of
                       possibilities)
  -s, --source=        Read an application from a .tas file (AOT format).
      --savestats      save the Stats object rather than the text output of the
                       profiler.
      --spew           Print an insanely verbose log of everything that happens.
                       Useful when debugging freezes or locks in complex code.
      --syslog         Log to syslog, not to file
  -u, --uid=           The uid to run as.
      --umask=         The (octal) file creation mask to apply.
      --version        Print version information and exit.
  -y, --python=        read an application from within a Python file (implies
```

**Comment by t3chn0m4g3** [comment]
This is fixed in upstream, once we move to Cowrie 1.6.0 the fix is applied as well. However I checked the logs of the last couple of days in none of which this error occured.

**Comment by t3chn0m4g3** [comment]
Next time add more context, the error does only occur while building the image.

**Comment by iukea1** [comment]
@t3chn0m4g3 getting this error after I build this image

**Comment by iukea1** [comment]
@t3chn0m4g3 thank you for looking into this !
