### ISSUE TITLE
Down Front when use Crawler (dirb)

### ISSUE THREAD

**Issue by AndreyMironenkoGit** [dtag-dev-sec/tpotce#550]
Hi.

When using dirb or any other crawler, the front falls, but the container keeps working. When accessing the server, it returns 504. Serviceability is only restored when the Tanner container has restarted.

snare.err
2020-02-17 13:23:01 ERROR:aiohttp.server:log_exception: Error handling request
2020-02-17 13:28:42 ERROR:snare.tanner_handler:submit_data: Exception:
Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/Snare-0.3.0-py3.7.egg/snare/tanner_handler.py", line 53, in submit_data
timeout=10.0
File "/usr/lib/python3.7/site-packages/aiohttp/client.py", line 391, in _request
await resp.start(conn)
File "/usr/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 770, in start
self._continue = None
File "/usr/lib/python3.7/site-packages/aiohttp/helpers.py", line 673, in exit
raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
2020-02-17 13:28:42 ERROR:aiohttp.server:log_exception: Error handling request

I tried to change the timeout to 20, but it just delayed the fall of the front by 10. I also tried to bypass the helpers.py exception with "pass" did not help either. I also checked the RAM load and everything was okay. The only thing that works is a strong slowdown of crawler, but on real traffic will be much more request and it will down again. Pls Help.

Best Regards

**Comment by t3chn0m4g3** [comment]
This seems an issue with Snare / Tanner. And you already opened an issue [there](https://github.com/mushorg/snare/issues/233).

**Comment by AndreyMironenkoGit** [comment]
I must close this Issue?

**Comment by t3chn0m4g3** [comment]
Let's keep it open for tracking.

**Comment by t3chn0m4g3** [comment]
This seems to be Tanner related, opened [issue](https://github.com/mushorg/tanner/issues/353) accordingly.

**Comment by Fosocles** [comment]
You can close this now. 
See [#353](https://github.com/mushorg/tanner/pull/362) for details of the bug/fix.

**Comment by t3chn0m4g3** [comment]
Thanks. I will keep it open, since I probably introduce the fix only with 20.06.
