### ISSUE TITLE
Installation failing, broken dependency in python3-distutils

### ISSUE THREAD

**Issue by Oogy** [dtag-dev-sec/tpotce#559]
Just for tracking and so others are aware, the latest release of python3-distutils breaks T-Pot installation with a bad dependency:

```
# apt -y install python3-distutils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-distutils : Depends: python3 (>= 3.8.0-1~) but 3.7.5-3 is to be installed
                     Depends: python3-lib2to3 (>= 3.6.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
It appears the issue has already been fixed, but I think it still needs to be released:
https://tracker.debian.org/news/1105519/accepted-python3-stdlib-extensions-382-2-source-into-unstable/

**Comment by t3chn0m4g3** [comment]
@Oogy Thanks for opening this. It seems it was resolved, at least my test installation worked fine.
Can you confirm?

**Comment by Oogy** [comment]
Confirmed :+1:

**Comment by t3chn0m4g3** [comment]
@Oogy Thanks!

**Comment by t3chn0m4g3** [comment]
There still seems to be a problem with that package. Reopening it to avoid duplicate issues.

**Comment by t3chn0m4g3** [comment]
The only package I con confirm has a problem because of #559 is `elasticsearch-curator`, which, by all means, does not explain the problems in this issue:
```
+ elasticdump@6.23.0
updated 1 package in 6.179s
Collecting elasticsearch-curator
  Using cached https://files.pythonhosted.org/packages/34/78/787a52834656f7f5dab6d709e38876c4d2604f0e1a16d17937d00330b0c5/elasticsearch-curator-5.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    WARNING: The wheel package is not available.
      Failed building wheel for pyyaml
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/tmp/pip-install-_3mfvt3p/elasticsearch-curator/setup.py", line 39, in <module>
        from cx_Freeze import setup, Executable
    ModuleNotFoundError: No module named 'cx_Freeze'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp5dlqn4sz', '--quiet', 'pyyaml==3.13']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_3mfvt3p/elasticsearch-curator/setup.py", line 144, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp5dlqn4sz', '--quiet', 'pyyaml==3.13']' returned non-zero exit status 1.
```

**Comment by faucherb94** [comment]
@t3chn0m4g3 Did you figure this out? I just ran into this same exact issue.

**Comment by t3chn0m4g3** [comment]
@faucherb94 With 19.03.3 release we moved to Debian 10.3 Stable. New installations will no longer be affected by this since the changes were only released into Debian Sid / Testing.
